export const Response_Msg = {
    Success: "Success",
    User_Fetched : "User data fetched",
    User_Created : "User created successfully!",
    User_Not_Found : "User is not registered!",
    Error : "An unexpected error occured",
    Connection_Error: "Error connecting to the database",
    Connected: "Successfully connected to database",
    LoggedIn: "Successfully logged in",
    Failed: "Login Failed!",
    Incorrect: "Invalid credentials!",
    Already: "User already exists",
    emailErr: "Email format is invalid",
    nameErr: "Please enter a name with atleast 4 characters",
    passErr: "Password must be at least 6 characters and include a number",
    token: "Token expired or invalid",
    resetLink: "Check your mail for a reset link",
    reset: "Try login with your new password",
};